dependencies:
  - name: postgresql
    version: 0.13.1
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: redis
    version: 3.3.3
    repository: https://kubernetes-charts.storage.googleapis.com/
