apiVersion: v1
description: Alert aggregation and management service
name: alerta
version: 0.0.1
appVersion: 5.2.5
home: http://alerta.io/
sources:
- https://github.com/alerta/alerta
- https://github.com/alerta/docker-alerta
maintainers:
- name: knorby
  email: kali.norby@softwaremotor.com
